### PR TITLE
fix: detect rules with plugin alias name or no plugin name

### LINKED ISSUE #226: Plugin doesn't check for typescript rules
My eslint config has typescript rule

```ts
'@typescript-eslint/no-unused-vars': ['error', {
  caughtErrors: 'none',
}],
```
eslint-plugin-oxlint is configured in eslint.config

```ts
  },
  ...buildFromOxlintConfigFile('./.oxlintrc.json'),
)
```

When I run `npx oxlint -c .oxlintrc.json || npx eslint` _unused var_ rule appear both in oxlint and eslint log. Same file, same line.

_oxlint log_
```
 × typescript-eslint(no-explicit-any): Unexpected any. Specify a different type.
   ╭─[src/shared/lib/capitalizeFirstLetter.ts:2:44]
 1 │ /** @description Foobar*/
 2 │ export const capitalizeFirstLetter = (str: any) => {
   ·                                            ───
 3 │   return str.trim().charAt(0).toUpperCase() + str.trim().slice(1)
   ╰────
```

_eslint log_
```
/path/to/my/project/src/shared/lib/capitalizeFirstLetter.ts
  2:44  error  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
```

### PR DESCRIPTION
**Pull request by Sysix**
closes #226

### CODE REVIEW

File: src/build-from-oxlint-config.ts [hunk 1]
```diff
@@ -112,34 +157,40 @@ const handleRulesScope = (
   rules: Record<string, 'off'>
 ): void => {
   for (const rule in oxlintRules) {
+    const eslintName = getEsLintRuleName(rule);
+
+    if (eslintName === undefined) {
+      // ToDo: output?
```
Comment (Sysix) [inline src/build-from-oxlint-config.ts:163]: oxlint is already outputting it. should we do the same too?

Comment (Boshen) [reply src/build-from-oxlint-config.ts:163]: Yes we should warn about it.

Comment (Sysix) [reply src/build-from-oxlint-config.ts]: done
